import type { Metadata } from "next";
import "./globals.css";
import { Manrope } from "next/font/google";

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={` ${manrope.className} h-full antialiased `}>
      <body
        className={`min-h-auto flex flex-col overflow-x-hidden bg-linear-to-b from-[#00010F] to-[#000442]`}
      >
        {children}
      </body>
    </html>
  );
}
